# Generated by Django 4.0.3 on 2022-04-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_image_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='..../images/'),
        ),
    ]
