# Generated by Django 4.0.3 on 2022-04-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_course_image_course_big_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='big_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='small_image',
        ),
        migrations.AddField(
            model_name='course',
            name='div_small_image',
            field=models.ImageField(blank=True, upload_to='images/course/div-small-images'),
        ),
        migrations.AddField(
            model_name='course',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='images/course/header-images'),
        ),
    ]
