# Generated by Django 4.0.3 on 2022-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_course_big_image_remove_course_small_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='div_small_image',
        ),
        migrations.AddField(
            model_name='course',
            name='div_image',
            field=models.ImageField(blank=True, upload_to='images/course/div-images'),
        ),
    ]
