# Generated by Django 4.0.3 on 2022-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_course_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='images/course/header-images'),
        ),
    ]
