# Generated by Django 4.0.3 on 2022-04-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_facultet'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='facultet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.facultet'),
        ),
    ]
