# Generated by Django 4.0.3 on 2022-04-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_course_facultet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='facultet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.facultet'),
        ),
    ]
