# Generated by Django 4.0.3 on 2022-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_course_facultet'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='option',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
