# Generated by Django 4.0.3 on 2022-04-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_option_course_option_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='option_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='facultet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.facultet'),
        ),
        migrations.AlterField(
            model_name='course',
            name='option_group',
            field=models.CharField(blank=True, help_text='Խմբային տարբերակի ուսանողների քանակը', max_length=100),
        ),
    ]
