# Generated by Django 4.0.3 on 2022-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_course_option_personal_alter_course_facultet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='armenian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='russian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='option_personal',
            field=models.BooleanField(default=False, help_text='Անհատական տարբերակ'),
        ),
    ]
