# Generated by Django 4.0.3 on 2022-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_course_armenian_course_english_course_russian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group_money',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='personal_money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
