# Generated by Django 4.0.3 on 2022-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_learningtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_topics',
            field=models.ManyToManyField(to='api.learningtopic'),
        ),
    ]
