# Generated by Django 4.0.3 on 2022-04-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_trainer_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='course', to='api.course'),
        ),
    ]
