# Generated by Django 4.0.3 on 2022-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_course_average_salary_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.FileField(blank=True, upload_to='images/course/certificates'),
        ),
    ]
