# Generated by Django 4.0.3 on 2022-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_course_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=50)),
                ('dsescription', models.TextField(max_length=500)),
            ],
        ),
    ]
