# Generated by Django 4.0.3 on 2022-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultet',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningtopic',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
