# Generated by Django 4.0.3 on 2022-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_studentwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_works',
            field=models.ManyToManyField(to='api.studentwork'),
        ),
    ]
