# Generated by Django 4.0.3 on 2022-05-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('screen', models.FileField(blank=True, upload_to='images/service/our-works')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='you_will_receive_icon1',
            field=models.FileField(blank=True, upload_to='images/service/you-will-receive'),
        ),
        migrations.AddField(
            model_name='service',
            name='you_will_receive_icon2',
            field=models.FileField(blank=True, upload_to='images/service/you-will-receive'),
        ),
        migrations.AddField(
            model_name='service',
            name='you_will_receive_icon3',
            field=models.FileField(blank=True, upload_to='images/service/you-will-receive'),
        ),
        migrations.AddField(
            model_name='service',
            name='you_will_receive_title1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='you_will_receive_title2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='you_will_receive_title3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
