# Generated by Django 4.0.3 on 2022-05-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_ourwork_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='our_works',
            field=models.ManyToManyField(to='api.ourwork'),
        ),
    ]
