# Generated by Django 4.0.3 on 2022-05-02 14:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_service_our_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dd',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
