# Generated by Django 4.0.3 on 2022-05-02 14:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_service_dd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='dd',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='BlogContent'),
        ),
    ]
