# Generated by Django 4.0.3 on 2022-05-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_service_dd'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='dd',
        ),
        migrations.AddField(
            model_name='service',
            name='website_types',
            field=models.ManyToManyField(to='api.websitetype'),
        ),
    ]
