# Generated by Django 4.0.3 on 2022-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_registertocourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertocourse',
            name='option',
            field=models.CharField(choices=[('Personal', 'Անհատակամ'), ('Group', 'Խմբային')], default='', max_length=15),
        ),
    ]
