# Generated by Django 4.0.3 on 2022-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_registertocourse_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertocourse',
            name='language',
            field=models.CharField(choices=[('Armenian', 'Հայերեն'), ('Russian', 'Ռուսերեն'), ('English', 'Անգլերեն')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='registertocourse',
            name='option',
            field=models.CharField(choices=[('Personal', 'Անհատական'), ('Group', 'Խմբային')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='registertocourse',
            name='place',
            field=models.CharField(choices=[('Yerevan', 'Երևան'), ('Region', 'Մարզ'), ('International', 'Միջազգային')], default='', max_length=15),
        ),
    ]
