# Generated by Django 4.0.3 on 2022-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_registertocourse_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertocourse',
            name='language',
            field=models.CharField(choices=[('Armenian', 'Հայերեն'), ('Russian', 'Русский'), ('English', 'English')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='registertocourse',
            name='place',
            field=models.CharField(choices=[('Yerevan', 'Երևան'), ('Region', 'Մարզերում'), ('International', 'Միջազգային')], default='', max_length=15),
        ),
    ]
