# Generated by Django 4.0.3 on 2022-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_registertocourse_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertocourse',
            name='language',
            field=models.CharField(choices=[('Հայերեն', 'Հայերեն'), ('Русский', 'Русский'), ('English', 'English')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='registertocourse',
            name='option',
            field=models.CharField(choices=[('Անհատական', 'Անհատական'), ('Խմբային', 'Խմբային')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='registertocourse',
            name='place',
            field=models.CharField(choices=[('Երևան', 'Երևան'), ('Մարզերում', 'Մարզերում'), ('Միջազգային', 'Միջազգային')], default='', max_length=15),
        ),
    ]
