# Generated by Django 4.0.3 on 2022-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_registertocourse_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertocourse',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
