# Generated by Django 4.0.3 on 2022-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_registertocourse_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(default=None)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
