# Generated by Django 4.0.3 on 2022-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_ordercall'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetype',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
