# Generated by Django 4.0.3 on 2022-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_header_subscribes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='facultet',
        ),
        migrations.AddField(
            model_name='course',
            name='facultet',
            field=models.ManyToManyField(to='api.facultet'),
        ),
    ]
