# Generated by Django 4.0.3 on 2022-05-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_course_facultet_course_facultet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='dsescription',
            new_name='description',
        ),
    ]
