# Generated by Django 4.0.3 on 2022-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_rename_dsescription_curriculum_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultet',
            name='learning_topics',
            field=models.ManyToManyField(to='api.learningtopic'),
        ),
    ]
