# Generated by Django 4.0.3 on 2022-05-07 18:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_facultet_learning_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
